export const CHANGE_INDEX_DATA = 'index/CHANGE_INDEX_DATA';
export const TOGGLE_ISPULLUPLOAD = 'index/TOGGLE_ISPULLUPLOAD';
export const ADD_NEWS_LIST = 'index/ADD_NEWS_LIST';
export const CHANGE_UDATED_DATE= 'index/CHANGE_UDATED_DATE';
export const TOGGLE_HEADER_SHOW= 'index/TOGGLE_HEADER_SHOW';
