export const CHANGE_LONG_COMMENTS = 'comments/CHANGE_LONG_COMMENTS';
export const CHANGE_SHORT_COMMENTS = 'comments/CHANGE_SHORT_COMMENTS';
export const CHANGE_COMMENTS_INFO = 'comments/CHANGE_COMMENTS_INFO';
export const TOGGLE_SHORTCOMMENTS_SHOW = 'comments/TOGGLE_SHORTCOMMENTS_SHOW';